[providers]
node = false

[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = []

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm install -g corepack@0.31.0",
  "corepack enable",
  "corepack prepare pnpm@10.33.0 --activate",
  "cd /app && pnpm install --frozen-lockfile"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cd /app && pnpm --filter @colonels-academy/web run build"
]

[start]
cmd = "cd /app && pnpm --filter @colonels-academy/database run db:deploy && pnpm --filter @colonels-academy/database run db:seed --skip-generate && pnpm --filter @colonels-academy/web run start"

[variables]
NIXPACKS_NO_MUSL = "1"
